[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rootseg"
version = "0.1"
description = "Root image preprocessing and segmentation"
requires-python = ">=3.9,<3.14"
authors = [
    {name = "Lionel Safar"}
]
dependencies = [
    "numpy",
    "torch",
    "torchvision",
    "opencv-python",
    "imageio",
    "Pillow",
    "scikit-learn",
    "scikit-image",
    "scipy",
    "tqdm",
    "optuna",
    "pandas",
    "matplotlib",
    "rich",
    "h5py",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]